### ISSUE TITLE
为什么不直接使用系统原生的auditd?

### ISSUE THREAD

**Issue by wcc526** [DianrongSecurity/AgentSmith-HIDS#1]
可以参考以下项目
https://github.com/slackhq/go-audit

打patch的方式容易引起系统不稳定， 系统原生自带的auditd不是更稳定? go-auditd也是可以通过netlink的方式获取到以上信息.

**Comment by EBWi11** [comment]
1.性能差
2.hook connect 没有source ip/port，不支持和我们的NIDS/CMDB联动
3.不支持Docker
4.netlink性能没有共享内存好，我们的方案是使用的共享内存
5.二次开发困难，比如我们想得到stdin/stdout fd path，无法扩展

第二点和第三点最为重要，因为我们的HIDS天然就是为了和NIDS进行联动来解决很多问题的，包括希望后期可以通过HIDS+CMDB+NIDS来实现一些微隔离的目的。所以放弃了auditd。

**Comment by CaledoniaProject** [comment]
同意，auditbeat 简单配置下就能实现相同的功能。audit 也是 netlink socket 的，开发老简单了，并不是你想的那样。

不过话说回来，这个软件只是信息采集吗？后端分析策略可以分享下不 :-)
