### ISSUE TITLE
驱动在Ubuntu下编译出错

### ISSUE THREAD

**Issue by lovewinxp** [DianrongSecurity/AgentSmith-HIDS#5]
好像驱动不兼容Ubuntu，make编译出错
版本信息：
Linux version 4.4.0-116-generic (buildd@lgw01-amd64-021) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.9) ) #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018

**Comment by EBWi11** [comment]
是的，目前我们的项目仅仅在centos7下进行过稳定性测试，并且由于我们内部的标准化我们也仅仅对centos7进行适配

**Comment by EBWi11** [comment]
具体支持版本信息请看readme

**Comment by mzeyong** [comment]
> 好像驱动不兼容Ubuntu，make编译出错
> 版本信息：
> Linux version 4.4.0-116-generic (buildd@lgw01-amd64-021) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.9) ) #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018

是因为内核代码出现了改动导致的，老哥可以看一下我的fork 的分支的修改记录，就可以使用了
